### ISSUE TITLE
Error: Cannot find module 'sdk/net/xhr'

### ISSUE THREAD

**Issue by daleharvey** [canuckistani/bz.js#25]
Trying to use bz in my browserified bundle and browserify spits back this message

**Comment by daleharvey** [comment]
I thought
```
  "browser": {
    "sdk/net/xhr": false
  },
```
would fix it, but doesnt look so

**Comment by daleharvey** [comment]
putting that in the bz package.json means my build can complete, but then I get 'ajax not supported in this browser' when I try running it

**Comment by daleharvey** [comment]
that ends up getting the request stuff all confused, if I comment out 

    // try {
    //   XMLHttpRequest = require("sdk/net/xhr").XMLHttpRequest; // Addon SDK
    // }
    // catch(e) {}

works fine

**Comment by canuckistani** [comment]
This is because bz.js tries to support the Add-on SDK, however I suspect that most consumers of bz.js are using it in web content or node.js settings. The SDK is definitely the odd man out.

I wonder of there is a path forward where we could just avoid this, remove the SDK-specific code and instead do some post-build shim process similar to browserify that adds in the xhr global?

**Comment by canuckistani** [comment]
This should *just work* now, but I've done relatively light testing. Open new issues against the REST port if you run into them.
